import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        // <ClerkProvider appearance={{ baseTheme: dark }}>
        <html lang="en" className="dark" suppressHydrationWarning>
            <body className={font.className}>
                <Toaster />
                {children}
            </body>
        </html>
        // </ClerkProvider>
    );
}
